[package]
name = "test-panic"
version = "0.1.0"
authors = ["Ted Mielczarek <ted@mielczarek.org>"]

[lib]
crate-type = ["staticlib"]

[profile.release]
opt-level = 2
debug = true
rpath = false
lto = true
debug-assertions = false
panic = "abort"
